#!/bin/bash

onserver=false

for name in "legbiter" "gurthang" "lobera" "sugari" "harpe" "shamshir" "galatine" "balmung"
do
    if [ `hostname` == $name ]
    then
	onserver=true
    fi
done

if [ $onserver == false ]
then
    echo "Journey planner API only accessible from CUED servers"
    echo "Please log in to CUED servers and try again."
    exit
fi

./journeyplannertest.py

xmllint --format journeyplannertest.xml > test.xml
mv test.xml journeyplannertest.xml

